// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPYrrnSQwjX6y53bUePTdZFfZVakr0Sv0',
    appId: '1:400960724338:web:efb0169c3ee0851718d1eb',
    messagingSenderId: '400960724338',
    projectId: 'women-safety-sos-d0cd8',
    authDomain: 'women-safety-sos-d0cd8.firebaseapp.com',
    storageBucket: 'women-safety-sos-d0cd8.firebasestorage.app',
    measurementId: 'G-XWZ1KR9M17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM_Rq291NY7XXVJNtkFO0cSdrXqRIZxyI',
    appId: '1:400960724338:android:62caf4f9442625c618d1eb',
    messagingSenderId: '400960724338',
    projectId: 'women-safety-sos-d0cd8',
    storageBucket: 'women-safety-sos-d0cd8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoviS4dhPFo0UrdnIyjvNJX9YdmKimL9g',
    appId: '1:400960724338:ios:35694848459d94a618d1eb',
    messagingSenderId: '400960724338',
    projectId: 'women-safety-sos-d0cd8',
    storageBucket: 'women-safety-sos-d0cd8.firebasestorage.app',
    iosBundleId: 'com.example.womenSafety',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoviS4dhPFo0UrdnIyjvNJX9YdmKimL9g',
    appId: '1:400960724338:ios:35694848459d94a618d1eb',
    messagingSenderId: '400960724338',
    projectId: 'women-safety-sos-d0cd8',
    storageBucket: 'women-safety-sos-d0cd8.firebasestorage.app',
    iosBundleId: 'com.example.womenSafety',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPYrrnSQwjX6y53bUePTdZFfZVakr0Sv0',
    appId: '1:400960724338:web:d47b2e88d449c54a18d1eb',
    messagingSenderId: '400960724338',
    projectId: 'women-safety-sos-d0cd8',
    authDomain: 'women-safety-sos-d0cd8.firebaseapp.com',
    storageBucket: 'women-safety-sos-d0cd8.firebasestorage.app',
    measurementId: 'G-74X3JS1B2P',
  );
}
